#A script to clean up everything which can be automatically generated by ./build
#
# make distclean or make maintainer-clean should clean up most things
# but still we want to clean up more
test -f Makefile && make clean
test -f Makefile && make distclean
rm -rf aclocal.m4 autom4te.cache Makefile.in depcomp INSTALL install-sh missing configure
