#A script to clean up everything which can be automatically generated by ./build
#
# make distclean or make maintainer-clean should clean up most things
# but still we want to clean up more
test -f Makefile && make clean 
test -f Makefile && make distclean 
rm -rf aclocal.m4 autom4te.cache Makefile.in config/depcomp INSTALL config/install-sh config/missing configure config/config.guess config/config.sub 
# be careful about this. Your project may contain other packages using Makefile.in
find -name Makefile.in -exec rm -rf {} \; 
